### PR TITLE
Utils: combine/remove unused states

### PR DESCRIPTION
**Pull request by danrabbit**
* `CONNECTED_WIFI` and `DISCONNECTED_WIRED` are never set
* There doesn't appear to be any difference between `FAILED_WIRED` and `FAILED_VPN`

### CODE REVIEW

**Comment by tintou** [comment]
As an occasional VPN user, it would be useful to have a specific message with "failed to connect to VPN" as this happens after the connection to network.

**Comment by danrabbit** [comment]
@tintou Yeah I think there’s probably a better way to get the device type though and not conflate with state like we’re doing here. My eventual goal is to use NM.DeviceState like in Switchboard

**Comment by jeremypw** [comment]
@danrabbit Is it your intention that this PR should merged and Corentin's issue dealt with in a later PR?

**Comment by danrabbit** [comment]
@jeremypw it sounds like Corentin is looking for a new feature and not that this branch would break an existing feature. So yes I think that would be better to move towards separating device type from state as using state directly from NM

**Review by jeremypw — APPROVED** [review]
No practical difference as things stand.

**Pull request merged**
