### PR TITLE
WifiMenuItem.vala: Display insecure icon for insecure networks

### LINKED ISSUE #27: Mark unsecured networks as insecure
Instead of marking encrypted connections as secure with a lock, we should mark unsecured networks as insecure with a warning or slashed-out lock icon. This helps educate users that secure should be the default while unsecured is the exception and potentially dangerous.

Launchpad Details: [#LP1651848](https://bugs.launchpad.net/bugs/1651848) Cassidy James Blaede - 2016-12-21 20:55:27 +0000

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #27 

This is a follow up from Cassidy's article on secure by default. I'm going to mark this as blocked just so it generates some discussion before we consider merging.

* Networks are now assumed to be secure and insecure networks are badged with `channel-insecure-symbolic`.

* Tooltips about the security status of a network show when hovering any part of the menu item for added visibility

screenshot from 2017-05-16 14 18 14

### CODE REVIEW

**Comment by danrabbit** [comment]
I wonder if we should use a different icon for networks with no password. I think in most cases these are public networks. So maybe it would be better to use an icon that indicates that instead of jumping straight to "insecure"

**Comment by cassidyjames** [comment]
My one critique is that we should probably also mark WEP networks as insecure since they can be automatically cracked in seconds and leak the data as bad as an unsecured network. But that could be a separate change. :)

**Comment by cassidyjames** [comment]
The problem with public networks without a password is that they are extremely insecure. I think we should still denote them even if they're public; their intended use does not affect the security of the connection :wink:

**Comment by cassidyjames** [comment]
@danrabbit following up. I've been using this for a while and am in favor of this change. We could roll it out to daily to get further feedback.

**Pull request merged**
